name: Reusable Deploy
on: 
  workflow_call: # allows this workflow to be called from other workflows
    inputs:
      artifact-name:
        description: Then name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading..."